server:
  port: ${port:40100}
spring:
  application:
    name: cloud-fav
  rabbitmq:
    host: ${rabbitmq_host}
    port: 5672
    username: guest
    password: guest
    virtualHost: /
  redis:
    host: ${redis_host}
    port:  6379
    timeout: 5000 #连接超时 毫秒
    jedis:
      pool:
        maxActive: 3
        maxIdle: 3
        minIdle: 1
        maxWait: -1 #连接池最大等行时间 -1没有限制
  datasource:
    #          driver-class-name: com.mysql.cj.jdbc.Driver
    #          url: jdbc:mysql://127.0.0.1:3307/lot_user?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8&autoReconnect=true
    #          username: root
    #          password: 878266
    #容器中的服务连接其它容器服务需要使用对应容器所在的ip和端口才行。
    druid:
      url: jdbc:mysql://${mysql_host}/cloud_fav?
      username: ${mysql_username}
      password: ${mysql_pwd}
      driverClassName: com.mysql.jdbc.Driver
      initialSize: 5  #初始建立连接数量
      minIdle: 5  #最小连接数量
      maxActive: 20 #最大连接数量
      maxWait: 30000  #获取连接最大等待时间，毫秒
      testOnBorrow: true #申请连接时检测连接是否有效
      testOnReturn: false #归还连接时检测连接是否有效
      timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
      minEvictableIdleTimeMillis: 300000
  jpa:
    hibernate:
      ddl-auto: create #连接在连接池的最小生存时间（毫秒）


xuecheng:
  elasticsearch:
    hostlist: ${elasticsearch_host}:9200 #多个结点中间用逗号分隔,需要提前建立索引和type。
  course:
    index: xc_course
    type: doc
    source_field: uid,title,createDate,url
  mq:
    #cms客户端监控的队列名称（不同的客户端监控的队列不能重复）
    queue: queue_cms_postpage_03
    routingKey: 5b30cba5f58b4411fc6cb1e5    #此routingKey为门户站点ID

